In [19]:
import pandas as pd
from matplotlib import pyplot as plt

In [20]:
df = pd.read_csv("nasdaq100.csv", sep=";")  # separating by ";"
df

        Date  Starting (USD)  Ending (USD)
0   01.01.24           16800         16500
1   01.12.23           15900         16100
2   01.11.23           15800         15300
3   01.10.23           16100         16200
4   01.09.23           16300         15700
5   01.08.23           16800         16400
6   01.07.23           15900         16200
7   01.06.23           15800         15500
8   01.05.23           16150         16100
9   01.04.23           16300         15800
10  01.03.23           16200         16200
11  01.02.23           16300         15700

In [21]:
df.isnull().sum()  # isnull() shows the whole df with true false value. .sum() shows every cols null value count

Date              0
Starting (USD)    0
Ending (USD)      0
dtype: int64

In [22]:
# df = df.drop('Date', axis=1)
df = df.drop(columns=["Date"])  # deletes date column
df

    Starting (USD)  Ending (USD)
0            16800         16500
1            15900         16100
2            15800         15300
3            16100         16200
4            16300         15700
5            16800         16400
6            15900         16200
7            15800         15500
8            16150         16100
9            16300         15800
10           16200         16200
11           16300         15700