# Video_2 => List comprehension and function

In [1]:
numbers = [1,2, 3,4,5]
squared_nums = [x**2 for x in numbers]
print("squared_nums - ", squared_nums)
even_nums = [x for x in numbers if x % 2 == 0]
print("even_nums - ", even_nums)

squared_nums -  [1, 4, 9, 16, 25]
even_nums -  [2, 4]

In [2]:
names = ["Abul", "Kabul", "Babul"]
ages = [25, 30, 28]
name_age_tuple = [(name, age) for name, age in zip(names,ages)] # zip helps to work with 2 lists together
print("name_age_tuple -", name_age_tuple)

name_age_tuple - [('Abul', 25), ('Kabul', 30), ('Babul', 28)]

# Video_3 => Data analysis with Pandas

In [3]:
import pandas as pd
# Series is a sequencial data structure like array, tuple
data = [10, 20, 30, 40, 50]
series = pd.Series(data)  # creating series from list
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
# creating series with custom index
index = ['a', 'b', 'c', 'd', 'e']
series_with_index = pd.Series(data, index=index)
print(series_with_index)

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [5]:
# Accessing elements in a series
print(series[0]) # value of index "0"
print(series_with_index['b']) # value of index "b"

10
20

In [6]:
# Performing operations on a Series
print(series * 2)
print(series_with_index + 5)
print(series[3] * 2)
print(series_with_index['b'] + 5)

0     20
1     40
2     60
3     80
4    100
dtype: int64
a    15
b    25
c    35
d    45
e    55
dtype: int64
80
25

In [7]:
# Filtering a Series
print(series[series > 30])

# Statistical operations on Series
print(series.mean())
print(series.std())

3    40
4    50
dtype: int64
30.0
15.811388300841896

In [8]:
# Useful methods and attributes
print(series.index)
print(series.values)
print(series.describe())
print(series_with_index.index)
print(series_with_index.values)
print(series_with_index.describe())

RangeIndex(start=0, stop=5, step=1)
[10 20 30 40 50]
count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
[10 20 30 40 50]
count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [9]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 45, 43],
    "City": ["Dhaka", "Ctg", "Dhaka", "Khulna"]
}
df = pd.DataFrame(data)
print(df)

      Name  Age    City
0    Alice   25   Dhaka
1      Bob   30     Ctg
2  Charlie   45   Dhaka
3    David   43  Khulna

In [10]:
# Basic statistics
print(df.describe())

# Accessing specific column
print("\nAges: ")
print(df["Age"])

# Filtering data
print("\nPeople older than 30 -")
print(df[df['Age'] > 30])

             Age
count   4.000000
mean   35.750000
std     9.776673
min    25.000000
25%    28.750000
50%    36.500000
75%    43.500000
max    45.000000

Ages:
0    25
1    30
2    45
3    43
Name: Age, dtype: int64

People older than 30 -
      Name  Age    City
2  Charlie   45   Dhaka
3    David   43  Khulna

In [11]:
# Grouping data
print(df["Age"].mean()) # shows mean of one column
print("\n Average age by city: ")
print(df.groupby("City")['Age'].mean()) # mean of ages after grouping by city name

35.75

 Average age by city:
City
Ctg       30.0
Dhaka     35.0
Khulna    43.0
Name: Age, dtype: float64

In [12]:
# Sorting data
print("\n Sort by age")
print(df.sort_values("Age"))

 Sort by age
      Name  Age    City
0    Alice   25   Dhaka
1      Bob   30     Ctg
3    David   43  Khulna
2  Charlie   45   Dhaka

# Video_4 => EDA Weather Dataset

In [22]:
df = pd.read_csv(r"C:\Users\tanvi\shuvo_ml\phitron_ml\ctg_weather_data.csv")
df

,Unnamed: 0,Station,Year,Month,Day,Rainfall,Sunshine,Humidity,Temperature
0,82544,Chittagong,1961,1,1,0.0,0.7,76.0,22.2
1,82545,Chittagong,1961,1,2,0.0,4.9,72.0,23.7
2,82546,Chittagong,1961,1,3,0.0,0.5,85.0,22.3
3,82547,Chittagong,1961,1,4,0.0,8.3,81.0,23.1
4,82548,Chittagong,1961,1,5,0.0,9.5,53.0,20.9
...,...,...,...,...,...,...,...,...,...
23005,105549,Chittagong,2023,12,27,0.0,4.5,83.0,22.3
23006,105550,Chittagong,2023,12,28,0.0,3.8,82.0,21.6
23007,105551,Chittagong,2023,12,29,0.0,6.8,76.0,21.7
23008,105552,Chittagong,2023,12,30,0.0,6.6,73.0,23.1
23009,105553,Chittagong,2023,12,31,0.0,7.6,69.0,23.5

In [29]:
df.head()  # shows first 5 records

,Unnamed: 0,Station,Year,Month,Day,Rainfall,Sunshine,Humidity,Temperature
0,82544,Chittagong,1961,1,1,0.0,0.7,76.0,22.2
1,82545,Chittagong,1961,1,2,0.0,4.9,72.0,23.7
2,82546,Chittagong,1961,1,3,0.0,0.5,85.0,22.3
3,82547,Chittagong,1961,1,4,0.0,8.3,81.0,23.1
4,82548,Chittagong,1961,1,5,0.0,9.5,53.0,20.9

In [30]:
df.tail()  # shows last 5 records

,Unnamed: 0,Station,Year,Month,Day,Rainfall,Sunshine,Humidity,Temperature
23005,105549,Chittagong,2023,12,27,0.0,4.5,83.0,22.3
23006,105550,Chittagong,2023,12,28,0.0,3.8,82.0,21.6
23007,105551,Chittagong,2023,12,29,0.0,6.8,76.0,21.7
23008,105552,Chittagong,2023,12,30,0.0,6.6,73.0,23.1
23009,105553,Chittagong,2023,12,31,0.0,7.6,69.0,23.5

In [31]:
df.describe() # shows overview of the dataset

,Unnamed: 0,Year,Month,Day,Rainfall,Sunshine,Humidity,Temperature
count,23010.000000,23010.000000,23010.000000,23010.000000,23010.000000,23010.000000,23010.000000,23010.000000
mean,94048.500000,1992.000000,6.523077,15.729205,7.897048,6.916152,78.848617,25.861177
std,6642.559183,18.184064,3.448738,8.800101,23.669308,3.348471,8.451316,3.391735
min,82544.000000,1961.000000,1.000000,1.000000,0.000000,0.000000,36.000000,13.900000
25%,88296.250000,1976.000000,4.000000,8.000000,0.000000,4.520000,74.000000,23.500000
50%,94048.500000,1992.000000,7.000000,16.000000,0.000000,8.000000,79.000000,26.900000
75%,99800.750000,2008.000000,10.000000,23.000000,3.000000,9.600000,84.000000,28.500000
max,105553.000000,2023.000000,12.000000,31.000000,511.000000,13.400000,100.000000,37.800000

In [32]:
df.shape  # shows rows and columns

(23010, 9)

In [33]:
df.dtypes  # shows data types of all the columns

Unnamed: 0       int64
Station         object
Year             int64
Month            int64
Day              int64
Rainfall       float64
Sunshine       float64
Humidity       float64
Temperature    float64
dtype: object